### ISSUE TITLE
Indented code blocks causes segment violation

### ISSUE THREAD

**Issue by mondeja** [dominickpastore/pymd4c#10]
I don't know if is an error with `md4c` or with bindings.

## Minimal reproducible example

```python
import md4c

def enter_block_callback(block, details):
    print("py -- ENTER BLOCK", block.name, details)

def leave_block_callback(block, details):
    print("py -- LEAVE BLOCK", block, details)

def enter_span_callback(block, details):
    print("py -- ENTER SPAN", block)

def leave_span_callback(block, details):
    print("py -- LEAVE SPAN", block)

def text_callback(block, text):
    print("py -- TEXT", text)


content = '''# Header

    some indented code block
    with two lines 

'''
parser = md4c.GenericParser()
parser.parse(content,
                     enter_block_callback,
                     leave_block_callback,
                     enter_span_callback,
                     leave_span_callback,
                     text_callback)
```

## OS

- Ubuntu 20.04.1 LTS
- Python 3.8.2
- x86_64

**Comment by dominickpastore** [comment]
Thanks for the report. I'm going to guess it's probably my code... I will take a look this afternoon.

**Comment by dominickpastore** [comment]
Missing attributes were causing a NULL dereference. This should be fixed now.

Hopefully there aren't other bugs that are so simple. It's not terribly complex code. Sometime soon, I plan to add a proper test suite, but I've had other things competing for my attention recently. Until then, I will keep calling this "beta."

**Comment by mondeja** [comment]
Thank you so much! I have seen the info text as NULL, but I didn't know how to handle it properly.

After lot of using, this was the unique failure that I have found. I will notify you if I find any other fault :+1:

**Comment by dominickpastore** [comment]
> After lot of using, this was the unique failure that I have found. I will notify you if I find any other bug that I couldn't fix

Thanks, that is good to hear!
