### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by mondeja** [dominickpastore/pymd4c#30]
Hi,

As Python 3.10 [was released a month ago](https://www.python.org/downloads/release/python-3100/), do you plan to release a new version supporting it?

Thanks

**Comment by dominickpastore** [comment]
Yes. I will work on this now. Hopefully should be out within a couple hours.

**Comment by dominickpastore** [comment]
Done, release 1.1.1 is out with builds for 3.10

**Comment by mondeja** [comment]
Great, thank you!
